name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  fabrication:
    runs-on: ubuntu-latest
    steps:
      - name: Obtention du code
        uses: actions/checkout@v4

      - name: Installatioon de Deno v2 bro
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Toutes les dépendances...
        run: deno install

      - name: Fabrication
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          deno run build

      - name: Téléversement des artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  publication_sur_l_internet:
    needs: fabrication
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
