name: GitHub Pages brrrrrrr

on:
  push:
    branches: [ main ]

jobs:
  github-pages:
    name: Je doit tout refaire pour GitHub Pages à cause du BASE_PATH
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Je télécharge le code source
        uses: actions/checkout@v3

      - name: J'installe Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: L'enfert des dépendances
        run: deno install --allow-scripts

      - name: Je fabrique le code illisible sauce GitHub
        run: deno task build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'

      - name: Je donne le code illisible
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .output/public

      - name: Déploiement final à GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  fabrication:
    name: Je prépare tout
    runs-on: ubuntu-latest

    steps:
      - name: Je télécharge le code source
        uses: actions/checkout@v3

      - name: J'installe Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: L'enfert des dépendances
        run: deno install --allow-scripts

      - name: Je fabrique le code illisible
        run: deno task build

      - name: Je donne le code illisible
        uses: actions/upload-artifact@v4
        with:
          name: resultat-fabrication
          path: .output/public

  cloudflare-pages:
    name: Je publie le site sur l'Internet (Cloudflare Pages)
    needs: fabrication
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Je prends le code illisible
        uses: actions/download-artifact@v4
        with:
          name: resultat-fabrication

      - name: Je le redonne à Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=${{ secrets.CLOUDFLARE_PROJECT }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  surge-sh:
    name: Je publie le site sur l'Internet (surge.sh)
    needs: fabrication
    runs-on: ubuntu-latest

    steps:
      - name: Je prends le code illisible
        uses: actions/download-artifact@v4
        with:
          name: resultat-fabrication

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g surge

      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
